# This file is used in development only, as the production database is managed by Coolify's native feature for that.
# If you bump the database version here, be sure to update the database accordingly on Coolify as well.

services:
  postgres:
    image: postgres:17.9
    ports:
      - ${POSTGRES_PORT-:5432}:5432
    environment:
      POSTGRES_USER: hackathons
      POSTGRES_DB: hackathons_test
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
