services:
  postgres:
    image: postgres:17.6
    ports:
      - ${POSTGRES_PORT-:5432}:5432
    environment:
      POSTGRES_USER: hackathons
      POSTGRES_DB: hackathons_test
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
