default: &defaults
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"

  name: "Hackathons"

  ignore_actions:
    - Rails::HealthController#show

development:
  <<: *defaults
  active: false

test:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
