default: &defaults
  push_api_key: "<%= Rails.application.credentials.dig(:appsignal, :push_api_key) %>"

  name: "Hackathons"

  ignore_actions:
    - Rails::HealthController#show

development:
  <<: *defaults
  active: false

test:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
