default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  username: hackathons
  host: 127.0.0.1
  gssencmode: disable # https://github.com/ged/ruby-pg/issues/311#issuecomment-561927000

development:
  <<: *local
  database: hackathons_development

test:
  <<: *local
  database: hackathons_test

production:
  <<: *default
  database: hackathons_production
