access-key-id: $LITESTREAM_ACCESS_KEY_ID
secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY

dbs:
- path: /storage/production.sqlite3
  replicas:
  - url: s3://${LITESTREAM_BUCKET}/db
    region: $LITESTREAM_REGION
